# .github/workflows/ci-cd.yml
name: CI/CD to Azure Container Apps (with .NET Aspire and azd)

on:
  push:
    branches:
      - main

env:
  AZURE_CONTAINER_REGISTRY_NAME: ${{ secrets.ACR_NAME }} 
  AZURE_RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP }} 
  AZURE_LOCATION: eastasia 
  AZURE_ENVIRONMENT_NAME: aspire-env-${{ github.run_number }} 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure Developer CLI (azd)
        uses: Azure/setup-azd@v2
        with:
          version: 'latest'

      - name: Restore, Build, and Deploy with azd
        run: |
          # Provision and deploy all services defined in your Aspire AppHost
          azd up --environment ${{ env.AZURE_ENVIRONMENT_NAME }} \
                 --location ${{ env.AZURE_LOCATION }} \
                 --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} \
                 --resource-group ${{ env.AZURE_RESOURCE_GROUP_NAME }} \
                 --force-image-build # Ensures new images are built on each run
        working-directory: ./AspireAppTest.AppHost 
        env: 
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
          AZURE_POSTGRES_PASSWORD: ${{ secrets.AZURE_POSTGRES_PASSWORD }}
          AZURE_POSTGRES_USER: ${{ secrets.AZURE_POSTGRES_USER }}

      - name: Get Azure Container App URLs
        run: |
          azd env get-values --output json > azd-env.json
          WEB_FRONTEND_URL=$(jq -r '.["WEB_FRONTEND_URL"]' azd-env.json)
          API_SERVICE_URL=$(jq -r '.["API_SERVICE_URL"]' azd-env.json) # Check the exact name azd uses for this output

          echo "WebFrontend URL: $WEB_FRONTEND_URL"
          echo "ApiService URL: $API_SERVICE_URL"
        working-directory: ./AspireAppTest.AppHost