# .github/workflows/ci-cd.yml
name: CI/CD to Azure Container Apps

on:
  push:
    branches:
      - main

env:
  ACR_NAME: ${{ secrets.ACR_NAME }}
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build & push ApiService
        uses: docker/build-push-action@v4
        with:
          context: ./AspireAppTest.ApiService
          file: ./AspireAppTest.ApiService/Dockerfile
          push: true
          tags: ${{ env.ACR_NAME }}.azurecr.io/apiservice:${{ env.IMAGE_TAG }}

      - name: Build & push WebFrontend
        uses: docker/build-push-action@v4
        with:
          context: ./AspireAppTest.Web
          file: ./AspireAppTest.Web/Dockerfile
          push: true
          tags: ${{ env.ACR_NAME }}.azurecr.io/webfrontend:${{ env.IMAGE_TAG }}

      - name: Deploy ApiService to CA
        uses: azure/container-apps-deploy-action@v1
        with:
          acrName: ${{ env.ACR_NAME }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: apiservice
          imageToDeploy: ${{ env.ACR_NAME }}.azurecr.io/apiservice:${{ env.IMAGE_TAG }}

      - name: Deploy WebFrontend to CA
        uses: azure/container-apps-deploy-action@v1
        with:
          acrName: ${{ env.ACR_NAME }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: webfrontend
          imageToDeploy: ${{ env.ACR_NAME }}.azurecr.io/webfrontend:${{ env.IMAGE_TAG }}
